image: docker:latest

services:
  - docker:dind

stages:
  - build

test:
  stage: build
  image: golang:1.14
  script:
  - go test -count=1 -v ./...

lint:
  stage: build
  image: golangci/golangci-lint:latest-alpine
  script:
    - golangci-lint run -v --timeout 2m --out-format tab -c .golangci.yml
  allow_failure: true

verify:
  stage: build
  script:
    - apk update && apk add git
    - ./verify.sh
  only:
    - branches
  except:
    - master
